apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.v95.io
spec:
  group: v95.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                exampleType:
                  type: string
                programmingLanguage:
                  type: string
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example